version: '3.1'

services:
  ruby:
    build:
      context: .
      dockerfile: ruby.dockerfile
    command: "socat TCP-LISTEN:6379,fork TCP:redis:6379"
    volumes:
      - ./csv:/out/

  redis:
    image: redis
